
# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
script = "script"
solc = "0.8.26"
src = "src"
test = "test"
libs = ["dependencies"]
fs_permissions = [{ access = "read", path = "deployment.toml" }]
ffi = true # Allow use of the ffi cheatcode in tests.

# Compiler options

via_ir = true
evm_version = 'cancun'
optimizer_runs = 10000
solc_version = "0.8.26"
# Do not append metadata hash to bytecode. We do not currently use it, and omitting it results in
# more stable build artifacts, which is important since we check the bytecode into git.
# For information about Solidity metadata, see https://docs.soliditylang.org/en/latest/metadata.html
bytecode_hash = "none"

[profile.deployment-test]
test = "./deployment-test"

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.0.2"

[soldeer]
# whether soldeer manages remappings
remappings_generate = true

# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = true

# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = true

# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = ""

# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"

# whether to install sub-dependencies or not. If true this wil install the dependencies of dependencies 1 level down.
recursive_deps = true
